name = "Pybtex"
uuid = "c8fbd874-22fe-482d-9730-5f9c4aadbab0"
authors = ["Rafael Alves Batista <rafaelab@users.noreply.github.com>"]
repo-url = "https://github.com/rafaelab/Pybtex.jl.git"
version = "0.1.4"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1.17.0"
LaTeXStrings = "1.4.0"
Printf = ">=1.10, <1.12"
PythonCall = "0.9.23"
Test = "1.11.0"

[targets]
docs = ["Documenter"]
test = ["Test"]
